version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: crm_postgres_db
    restart: always
    environment:
      POSTGRES_USER: aletl10
      POSTGRES_PASSWORD: Alucard10!
      POSTGRES_DB: crm_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_crm_data:/var/lib/postgresql/data

volumes:
  postgres_crm_data: